language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
services: mongodb
install:
  - "pip install tornado --use-mirrors"
  - "pip install pymongo --use-mirrors"
script: py.test
notifications:
  email: false